version: '3'

volumes:
  public-data:
  tmp-data:
  log-data:

services:
  web:
    build: .
    command: 'bundle exec puma -C config/puma.rb -e production'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      # volumesを通じてnginxとファイルを共有している
      - 'public-data:/app/public'
      - 'tmp-data:/app/tmp'
      - 'log-data:/app/log'
    tty: true
    stdin_open: true

  nginx:
    build:
      context: containers/nginx
      dockerfile: Dockerfile.prod
    volumes:
      # volumesを通じてrailsとファイルを共有している
      - 'public-data:/app/public'
      - 'tmp-data:/app/tmp'
    ports:
      - '80:80'
    depends_on:
      - web